MrCCProject:
	g++ -m64 mapper.cpp -o mapper
	g++ -m64 reducer.cpp -o reducer
	g++ -m64 merge.cpp CPointSet.cpp -o merge
	g++ -m64 genDimensions.cpp -o genDimensions
	g++ -m64 updateDimensions.cpp -o updateDimensions

spotless: 
	  \rm -f mapper
	  \rm -f reducer
	  \rm -f merge
	  \rm -f genDimensions
	  \rm -f updateDimensions

